# Reconocimento de Tokens - Daniel Charua - A01017419 - 18/10/18
from globalTypes import *
regular_expresions = [
(r'[ \s\n\t]+',               TokenType.SPACE),
(r'',                         TokenType.SPACE),
(r'#[^\n]*',                  TokenType.SPACE),
(r'\$',                       TokenType.ENDFILE),
(r'\{',                       TokenType.RESERVED),
(r'\}',                       TokenType.RESERVED),
(r'\[',                       TokenType.RESERVED), 
(r'\]',                       TokenType.RESERVED),     
(r'\(',                       TokenType.RESERVED),
(r'\)',                       TokenType.RESERVED),
(r'\/\*(\*(?!\/)|[^*])*\*\/', TokenType.COMMENT),
(r';',                        TokenType.RESERVED),
(r',',                        TokenType.RESERVED),
(r'\+',                       TokenType.RESERVED),
(r'-',                        TokenType.RESERVED),
(r'\*',                       TokenType.RESERVED),
(r'/',                        TokenType.RESERVED),
(r'<=',                       TokenType.RESERVED),
(r'<',                        TokenType.RESERVED),
(r'>=',                       TokenType.RESERVED),
(r'>',                        TokenType.RESERVED),
(r'==',                       TokenType.RESERVED),
(r'!=',                       TokenType.RESERVED),
(r'=',                        TokenType.RESERVED),
(r'else',                     TokenType.RESERVED),
(r'if',                       TokenType.RESERVED),
(r'int',                      TokenType.RESERVED),
(r'return',                   TokenType.RESERVED),
(r'void',                     TokenType.RESERVED),
(r'while',                    TokenType.RESERVED),
(r'[0-9]+[a-zA-Z]+',          TokenType.ERROR),
(r'[0-9]+',                   TokenType.INT),
(r'[a-zA-Z_][0-9a-zA-Z_]*',   TokenType.ID)]
